name: korean_dictionary
description: Korean dictionary API - Interface for the open API services that are provided by the National Institute of Korean Language.
version: 0.0.1
homepage: https://github.com/hyungtaecf/korean_dictionary
repository: https://github.com/hyungtaecf/korean_dictionary

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  characters: ^1.3.0
  collection: ^1.17.2
  http: ^1.1.0
  xml: ^6.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.3

screenshots:
  - description: "Logo of the National Institute of Korean Language"
    path: "screenshots/nikl_logo.png"

topics:
  - korean
  - hangul
  - dictionary
  - language
